import express from "express";
import IPDWardCharges from "../../API/IPD/Master/IPDWardCharges.mjs";
import IPDBeds from "../../API/IPD/Master/IPDBeds.mjs";
import serviceCharges from "../../API/IPD/Master/IPDServiceCharges.mjs";
import ConsultantCharges from "../../API/IPD/Master/ConsultantCharges.mjs";
import DSCharges from "../../API/IPD/Master/DSCharges.mjs";
import MRReg from "../../API/IPD/Patient/PatientRegistration.mjs";
import Reservation from "../../API/IPD/Patient/Reservation.mjs";
import Shift from "../../API/IPD/Shift/Shift.mjs";
import Admission from "../../API/IPD/Patient/Admission.mjs";
import ConsultantVisit from "../../API/IPD/OtherTransactions/ConsultantVisit.mjs";
import WardCharges from "../../API/IPD/OtherTransactions/WardCharges.mjs";
import ProcedureCharges from "../../API/IPD/OtherTransactions/ProcedureCharges.mjs";
import AddServiceCharges from "../../API/IPD/OtherTransactions/AddServiceCharges.mjs";
import RoomTransfer from "../../API/IPD/OtherTransactions/WardTransfer.mjs";
import PaymentReciept from "../../API/IPD/Payment/PaymentReciept.mjs";
import RunningBill from "../../API/IPD/OtherTransactions/RunningBill.mjs";
import DischargeSummary from "../../API/IPD/Discharge/DischargeSummary.mjs";
import PatientDischarge from "../../API/IPD/Discharge/PatientDischarge.mjs";
import ReAdmission from "../../API/IPD/Discharge/ReAdmission.mjs";
import FinalBill from "../../API/IPD/Discharge/FinalBill.mjs";
import PaymentRefund from "../../API/IPD/Payment/PaymentRefund.mjs";

const router = express.Router();

router.use(IPDWardCharges);
router.use(IPDBeds);
router.use(serviceCharges);
router.use(ConsultantCharges);
router.use(DSCharges);
router.use(MRReg);
router.use(Reservation);
router.use(Shift);
router.use(Admission);
router.use(ConsultantVisit);
router.use(WardCharges);
router.use(ProcedureCharges);
router.use(AddServiceCharges);
router.use(RoomTransfer);
router.use(PaymentReciept);
router.use(PaymentRefund);
router.use(RunningBill);
router.use(DischargeSummary);
router.use(PatientDischarge);
router.use(ReAdmission);
router.use(FinalBill);

export default router;
